name: "NTFY"
description: "NTFY notification server addon"
version: "0.1.4"
slug: "ntfy"
url: "https://github.com/mrschloemp/ntfy-addon-HomeAssistant"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  80/tcp: 8000
